on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "lily-poodle"
  AZURE_WEBAPP_PACKAGE_PATH: "dist"
  NODE_VERSION: "14"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "npm install, build, and test"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
